const CONFIG = {
    titleWeb: "Hưng Xin Lỗi Hà Linh",
    introTitle: 'Hà Linh à, anh xin lỗi bé',
    introDesc: `Anh biết bé đang dỗi mà,
    Nhưng anh chỉ muốn bé hiểu rằng,
    Mỗi phút giây anh đều nhớ em,
    Chỉ muốn em cười thôi, đừng dỗi nữa nhé.`,
    btnIntro: '^^Anh Xin Lỗi^^',
    title: 'Em có dỗi anh nhiều không? 🥺',
    desc: 'Anh biết em đang giận, nhưng làm sao anh sống thiếu em được chứ? 😔',
    btnYes: 'Em tha lỗi cho anh nhé <33',
    btnNo: 'Chưa đâu :3',
    question: 'Anh chỉ muốn em hiểu, em là người quan trọng nhất với anh. Em có thể tha thứ cho anh không? <3',
    btnReply: 'Gửi lời xin lỗi cho em <3',
    reply: 'Anh xin lỗi vì đã làm em buồn. Anh yêu em và không bao giờ làm em dỗi nữa âuuuu! <33333333',
    mess: 'Troi ui iu má ni nhìu lứmmmmm 😘😘',
    messDesc: 'Cố làm bài nhanh để nghỉ ngơi i nề, thương bé iu của tui lắm gòi 🥺',
    btnAccept: 'Chúc bé iu ngủ ngon 😘',
    messLink: 'https://www.messenger.com/e2ee/t/29436420072615515/'
}
