const CONFIG = {
    titleWeb: "Anh Xin Lỗi Hà Linh",
    introTitle: 'Hà Linh à, anh xin lỗi',
    introDesc: `Anh biết em đang giận mà,
    Nhưng anh chỉ muốn em hiểu rằng,
    Mỗi phút giây anh đều nhớ em,
    Chỉ muốn em cười thôi, đừng giận nữa nhé.`,
    btnIntro: '^^Anh Xin Lỗi^^',
    title: 'Em có giận anh nhiều không? 🥺',
    desc: 'Anh biết em đang giận, nhưng làm sao anh sống thiếu em được chứ? 😔',
    btnYes: 'Anh tha lỗi cho anh nhé <33',
    btnNo: 'Chưa đâu :3',
    question: 'Anh chỉ muốn em hiểu, em là người quan trọng nhất với anh. Em có thể tha thứ cho anh không? <3',
    btnReply: 'Gửi lời xin lỗi cho em <3',
    reply: 'Anh xin lỗi vì đã làm em buồn. Anh yêu em và không bao giờ muốn thấy em giận đâu! <33333333',
    mess: 'Cảm ơn em đã hiểu, anh yêu em nhiều lắm 🥰. Anh sẽ không làm em buồn nữa đâu 😘😘',
    messDesc: 'Tối nay 7h, nếu em muốn, anh sẽ đến đón em đi chơi, làm lành nhé.',
    btnAccept: 'Ok, anh chờ em <3',
    messLink: 'https://github.com/zukahai/Confess-Crush' //link mess của các bạn. VD: https://www.facebook.com/messages/t/100014188333536
}
